In [73]:
import numpy as np

In [74]:
A = np.random.randint(0,3,size=(2,3))
x = np.random.randint(0,3,size=(3,))

print(A, x, A @ x, sep='\n----------\n')

[[0 2 2]
 [2 0 0]]
----------
[0 0 2]
----------
[4 0]


In [75]:
A = np.random.randint(0,3,size=(2,3))
x = np.random.randint(0,3,size=(3,1))

print(A, x, A @ x, sep='\n----------\n')

[[1 1 2]
 [1 1 1]]
----------
[[2]
 [0]
 [0]]
----------
[[2]
 [2]]


In [77]:
A = np.random.randint(0,3,size=(3,2,2))
B = np.random.randint(0,3,size=  (2,3))

print(A, B, A @ B, sep='\n----------\n')

[[[2 2]
  [2 1]]

 [[1 2]
  [0 2]]

 [[2 1]
  [0 1]]]
----------
[[2 1 0]
 [2 1 0]]
----------
[[[8 4 0]
  [6 3 0]]

 [[6 3 0]
  [4 2 0]]

 [[6 3 0]
  [2 1 0]]]


In [78]:
# same operation as above
# (2,2) @ (2,3).broadcast_3_times
A = np.random.randint(0,3,size=(3,2,2))
B = np.random.randint(0,3,size=(1,2,3))

print(A, B, A @ B, sep='\n----------\n')

[[[1 0]
  [0 0]]

 [[2 1]
  [2 2]]

 [[2 1]
  [0 2]]]
----------
[[[2 0 1]
  [2 2 0]]]
----------
[[[2 0 1]
  [0 0 0]]

 [[6 2 2]
  [8 4 2]]

 [[6 2 2]
  [4 4 0]]]


In [79]:
# 3 item-wise [(2,2) @ (2,3)]
A = np.random.randint(0,3,size=(3,2,2))
B = np.random.randint(0,3,size=(3,2,3))

print(A, B, A @ B, sep='\n----------\n')

[[[1 2]
  [0 1]]

 [[2 0]
  [1 1]]

 [[0 1]
  [2 2]]]
----------
[[[0 0 2]
  [0 0 2]]

 [[1 0 2]
  [2 1 1]]

 [[2 2 1]
  [1 1 0]]]
----------
[[[0 0 6]
  [0 0 2]]

 [[2 0 4]
  [3 1 3]]

 [[1 1 0]
  [6 6 2]]]


In [85]:
# 2 * [(3,2,2) @ (2,3).broadcast_3_times]
A = np.random.randint(0,3,size=  (3,2,2))
B = np.random.randint(0,3,size=(2,1,2,3))

print(A, B, A @ B, sep='\n----------\n')

[[[1 0]
  [2 1]]

 [[2 0]
  [0 1]]

 [[0 2]
  [0 2]]]
----------
[[[[2 2 0]
   [0 0 0]]]


 [[[0 2 1]
   [0 0 0]]]]
----------
[[[[2 2 0]
   [4 4 0]]

  [[4 4 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]


 [[[0 2 1]
   [0 4 2]]

  [[0 4 2]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]]


In [87]:
# 2 * {3 item-wise [(2,2) @ (2,3)]}
A = np.random.randint(0,3,size=  (3,2,2))
B = np.random.randint(0,3,size=(2,3,2,3))

print(A, B, A @ B, sep='\n----------\n')

[[[1 2]
  [0 2]]

 [[0 1]
  [2 0]]

 [[1 2]
  [0 0]]]
----------
[[[[0 1 2]
   [0 1 1]]

  [[1 1 2]
   [2 0 1]]

  [[2 2 2]
   [2 1 2]]]


 [[[1 0 2]
   [1 2 0]]

  [[1 2 1]
   [1 0 0]]

  [[2 0 0]
   [2 0 0]]]]
----------
[[[[0 3 4]
   [0 2 2]]

  [[2 0 1]
   [2 2 4]]

  [[6 4 6]
   [0 0 0]]]


 [[[3 4 2]
   [2 4 0]]

  [[1 0 0]
   [2 4 2]]

  [[6 0 0]
   [0 0 0]]]]
